ALTER TABLE "transactions" ALTER COLUMN "reference" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "transactions" ALTER COLUMN "notes" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "transactions" ALTER COLUMN "tx_hash" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "transactions" ALTER COLUMN "wallet_address" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "transactions" ALTER COLUMN "verification_note" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "transactions" ALTER COLUMN "nowpayments_payment_id" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "transactions" ALTER COLUMN "nowpayments_status" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "bet_selections" ALTER COLUMN "score_at_placement" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "bets" ALTER COLUMN "settled_at" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "bets" ALTER COLUMN "settled_payout" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "promotions" ALTER COLUMN "bonus_amount" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "promotions" ALTER COLUMN "min_deposit" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "promotions" ALTER COLUMN "max_claims" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "promotions" ALTER COLUMN "expires_at" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "sport_controls" ALTER COLUMN "margin_override" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "self_exclusions" ALTER COLUMN "duration_hours" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "self_exclusions" ALTER COLUMN "ends_at" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "self_exclusions" ALTER COLUMN "reason" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "self_exclusions" ALTER COLUMN "lifted_at" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "self_exclusions" ALTER COLUMN "lifted_by_admin_id" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "user_limits" ALTER COLUMN "pending_amount_usdt" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "user_limits" ALTER COLUMN "pending_effective_at" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "price_boosts" ALTER COLUMN "max_stake" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "price_boosts" ALTER COLUMN "expires_at" SET DEFAULT NULL;--> statement-breakpoint
ALTER TABLE "price_boosts" ALTER COLUMN "created_by" SET DEFAULT NULL;