kind = "web"
previewPath = "/api"
title = "Xing Huang API"
version = "1.0.0"
id = "artifacts/api-server"
router = "path"

[[services]]
name = "api"
paths = ["/api"]
localPort = 5000

[services.development]
run = "pnpm --filter @workspace/api-server run dev"

[services.development.env]
PORT = "5000"
NODE_ENV = "development"

[services.production]
run = "pnpm --filter @workspace/api-server run start"

[services.production.env]
PORT = "5000"
NODE_ENV = "production"

[services.production.health.startup]
path = "/api/health"
