import { Link } from 'wouter';
import { Header } from '@/components/Header';
import { ArrowLeft, Lock } from 'lucide-react';

const SECTIONS = [
  {
    title: 'What We Collect',
    body: 'We collect information you provide at registration (name, email, date of birth) and data generated by your activity on the platform (bet history, session logs, device type, IP address). We do not sell your personal data to third parties.',
  },
  {
    title: 'How We Use It',
    body: 'Your data is used to operate your account, process bets, detect fraud, comply with legal obligations, and improve the platform. We may send you service-related notifications; you can opt out of marketing emails at any time.',
  },
  {
    title: 'Data Sharing',
    body: 'We share data only with our licensed payment processors, identity verification providers, and regulatory authorities when legally required. All third-party partners are contractually bound to handle your data securely.',
  },
  {
    title: 'Cookies',
    body: 'GoBet uses essential cookies to keep you logged in and remember your preferences (e.g. odds format). Analytics cookies help us understand usage patterns. You can manage cookie preferences in your browser settings.',
  },
  {
    title: 'Data Retention',
    body: 'We retain account data for 5 years after account closure to meet AML and regulatory requirements. Anonymised analytics data may be retained indefinitely.',
  },
  {
    title: 'Your Rights',
    body: 'Under GDPR you have the right to access, correct, or delete your personal data; to restrict or object to processing; and to data portability. Submit requests to privacy@oddschain.io. We respond within 30 days.',
  },
  {
    title: 'Security',
    body: 'All data is encrypted in transit (TLS 1.3) and at rest (AES-256). Access to personal data is restricted to authorised personnel only. We conduct regular security audits.',
  },
];

export function Privacy() {
  return (
    <div className="min-h-screen bg-[#0B0F14] text-[#F8FAFC]">
      <Header />
      <main className="max-w-2xl mx-auto px-6 py-10">
        <Link href="/" className="inline-flex items-center gap-1.5 text-xs text-[#94A3B8]/60 hover:text-[#00DFA9] transition-colors mb-8">
          <ArrowLeft className="h-3.5 w-3.5" /> Back
        </Link>

        <div className="flex items-center gap-3 mb-8">
          <div className="w-9 h-9 rounded-xl bg-[#38BDF8]/10 border border-[#38BDF8]/20 flex items-center justify-center">
            <Lock className="h-4 w-4 text-[#38BDF8]" />
          </div>
          <div>
            <h1 className="text-xl font-black tracking-tight">Privacy Policy</h1>
            <p className="text-xs text-[#94A3B8]/50 mt-0.5">Last updated: 1 January 2026</p>
          </div>
        </div>

        <div className="space-y-6">
          {SECTIONS.map((s) => (
            <div key={s.title} className="rounded-xl bg-[#121821] border border-[#253241] px-5 py-4">
              <h2 className="text-sm font-bold text-[#F8FAFC] mb-2">{s.title}</h2>
              <p className="text-[13px] text-[#94A3B8]/70 leading-relaxed">{s.body}</p>
            </div>
          ))}
        </div>

        <p className="mt-8 text-[10px] text-[#94A3B8]/30 text-center">
          Privacy enquiries: <span className="text-[#38BDF8]/60">privacy@oddschain.io</span>
        </p>
      </main>
    </div>
  );
}
