/**
 * Team logo URL lookup — maps club/team names to publicly-accessible CDN images.
 *
 * Sources:
 *   Soccer  → ESPN CDN  https://a.espncdn.com/i/teamlogos/soccer/500/{id}.png
 *   NBA     → ESPN CDN  https://a.espncdn.com/i/teamlogos/nba/500/{abbrev}.png
 *   NFL     → ESPN CDN  https://a.espncdn.com/i/teamlogos/nfl/500/{abbrev}.png
 *
 * Aliases (short names, alternate spellings) are included so both mock data
 * and real Odds-API names resolve correctly.
 *
 * If a name is not found here the TeamBadge component falls back to a styled
 * initials circle.
 */

const E = (id: number) => `https://a.espncdn.com/i/teamlogos/soccer/500/${id}.png`;
const N = (a: string) => `https://a.espncdn.com/i/teamlogos/nba/500/${a}.png`;
const F = (a: string) => `https://a.espncdn.com/i/teamlogos/nfl/500/${a}.png`;

const LOGOS: Record<string, string> = {
  // ── Premier League ────────────────────────────────────────────────────────
  'Arsenal':                   E(359),
  'Chelsea':                   E(363),
  'Manchester City':           E(382),
  'Man City':                  E(382),
  'Manchester United':         E(360),
  'Manchester Utd':            E(360),
  'Man United':                E(360),
  'Man Utd':                   E(360),
  'Liverpool':                 E(364),
  'Liverpool FC':              E(364),
  'Tottenham Hotspur':         E(367),
  'Tottenham':                 E(367),
  'Spurs':                     E(367),
  'Aston Villa':               E(361),
  'Newcastle United':          E(397),
  'Newcastle':                 E(397),
  'West Ham United':           E(371),
  'West Ham':                  E(371),
  'Brighton & Hove Albion':    E(331),
  'Brighton':                  E(331),
  'Brentford':                 E(333),
  'Brentford FC':              E(333),
  'Fulham':                    E(370),
  'Fulham FC':                 E(370),
  'Crystal Palace':            E(384),
  'Wolverhampton Wanderers':   E(380),
  'Wolves':                    E(380),
  'Everton':                   E(368),
  'Everton FC':                E(368),
  'Nottingham Forest':         E(393),
  'Bournemouth':               E(349),
  'AFC Bournemouth':           E(349),
  'Sheffield United':          E(388),
  'Burnley':                   E(379),
  'Burnley FC':                E(379),
  'Luton Town':                E(377),
  'Leicester City':            E(375),
  'Leicester':                 E(375),
  'Leeds United':              E(357),
  'Leeds':                     E(357),
  'Southampton':               E(362),
  'Watford':                   E(372),
  'Norwich City':              E(387),
  'Norwich':                   E(387),
  'Ipswich Town':              E(373),
  'Ipswich':                   E(373),
  'Sunderland':                E(390),
  'Middlesbrough':             E(382),
  'Swansea City':              E(392),
  'Cardiff City':              E(356),
  'Queens Park Rangers':       E(386),
  'QPR':                       E(386),
  'Reading':                   E(399),
  'Derby County':              E(366),
  'Coventry City':             E(365),
  'Stoke City':                E(389),
  'Blackburn Rovers':          E(354),

  // ── La Liga ───────────────────────────────────────────────────────────────
  'Real Madrid':               E(86),
  'Real Madrid CF':            E(86),
  'FC Barcelona':              E(83),
  'Barcelona':                 E(83),
  'Atletico Madrid':           E(1068),
  'Atlético Madrid':           E(1068),
  'Atletico de Madrid':        E(1068),
  'Sevilla':                   E(243),
  'Sevilla FC':                E(243),
  'Real Sociedad':             E(89),
  'Villarreal':                E(102),
  'Villarreal CF':             E(102),
  'Real Betis':                E(244),
  'Real Betis Balompié':       E(244),
  'Valencia':                  E(94),
  'Valencia CF':               E(94),
  'Athletic Bilbao':           E(93),
  'Athletic Club':             E(93),
  'Celta Vigo':                E(246),
  'RC Celta de Vigo':          E(246),
  'Getafe':                    E(3842),
  'Getafe CF':                 E(3842),
  'Rayo Vallecano':            E(245),
  'Osasuna':                   E(248),
  'CA Osasuna':                E(248),
  'Girona':                    E(3839),
  'Girona FC':                 E(3839),
  'Las Palmas':                E(247),
  'UD Las Palmas':             E(247),
  'Mallorca':                  E(250),
  'RCD Mallorca':              E(250),
  'Almeria':                   E(2892),
  'UD Almería':                E(2892),
  'Cadiz':                     E(4024),
  'Cádiz CF':                  E(4024),
  'Granada':                   E(1080),
  'Granada CF':                E(1080),
  'Deportivo Alaves':          E(242),
  'Leganés':                   E(6794),
  'Espanyol':                  E(88),
  'RCD Espanyol':              E(88),
  'Valladolid':                E(240),
  'Real Valladolid':           E(240),

  // ── Bundesliga ────────────────────────────────────────────────────────────
  'Bayern Munich':             E(132),
  'FC Bayern Munich':          E(132),
  'FC Bayern München':         E(132),
  'Borussia Dortmund':         E(124),
  'BVB':                       E(124),
  'RB Leipzig':                E(23826),
  'Bayer Leverkusen':          E(131),
  'Bayer 04 Leverkusen':       E(131),
  'Eintracht Frankfurt':       E(127),
  'Wolfsburg':                 E(137),
  'VfL Wolfsburg':             E(137),
  'Freiburg':                  E(126),
  'SC Freiburg':               E(126),
  'Borussia Monchengladbach':  E(125),
  'Borussia Mönchengladbach':  E(125),
  'Mainz':                     E(133),
  'Mainz 05':                  E(133),
  '1. FSV Mainz 05':          E(133),
  'Hoffenheim':                E(10768),
  'TSG Hoffenheim':            E(10768),
  'Augsburg':                  E(19069),
  'FC Augsburg':               E(19069),
  'Werder Bremen':             E(138),
  'SV Werder Bremen':          E(138),
  'Union Berlin':              E(10764),
  '1. FC Union Berlin':        E(10764),
  'VfB Stuttgart':             E(135),
  'Stuttgart':                 E(135),
  'Darmstadt':                 E(30975),
  'SV Darmstadt 98':          E(30975),
  'Cologne':                   E(128),
  '1. FC Köln':               E(128),
  'Koln':                      E(128),
  'Heidenheim':                E(63849),
  '1. FC Heidenheim':         E(63849),
  'Schalke':                   E(136),
  'FC Schalke 04':             E(136),
  'Hamburger SV':              E(130),
  'HSV':                       E(130),
  'Hertha Berlin':             E(129),
  'Hertha BSC':                E(129),

  // ── Serie A ───────────────────────────────────────────────────────────────
  'Juventus':                  E(111),
  'Juventus FC':               E(111),
  'AC Milan':                  E(103),
  'Inter Milan':               E(110),
  'Internazionale':            E(110),
  'FC Internazionale Milano':  E(110),
  'Roma':                      E(104),
  'AS Roma':                   E(104),
  'Napoli':                    E(112),
  'SSC Napoli':                E(112),
  'Lazio':                     E(106),
  'SS Lazio':                  E(106),
  'Fiorentina':                E(109),
  'ACF Fiorentina':            E(109),
  'Atalanta':                  E(108),
  'Atalanta BC':               E(108),
  'Torino':                    E(113),
  'Torino FC':                 E(113),
  'Bologna':                   E(105),
  'Bologna FC':                E(105),
  'Sassuolo':                  E(8945),
  'US Sassuolo':               E(8945),
  'Udinese':                   E(115),
  'Udinese Calcio':            E(115),
  'Sampdoria':                 E(114),
  'UC Sampdoria':              E(114),
  'Genoa':                     E(107),
  'Genoa CFC':                 E(107),
  'Cagliari':                  E(100),
  'Cagliari Calcio':           E(100),
  'Empoli':                    E(7484),
  'Empoli FC':                 E(7484),
  'Salernitana':               E(52462),
  'US Salernitana':            E(52462),
  'Lecce':                     E(10837),
  'US Lecce':                  E(10837),
  'Hellas Verona':             E(10700),
  'Monza':                     E(65068),
  'AC Monza':                  E(65068),
  'Frosinone':                 E(3837),
  'Frosinone Calcio':          E(3837),
  'Venezia':                   E(116),
  'Venezia FC':                E(116),
  'Como':                      E(5918),
  'Como 1907':                 E(5918),
  'Parma':                     E(117),
  'Parma Calcio':              E(117),

  // ── Ligue 1 ───────────────────────────────────────────────────────────────
  'PSG':                       E(160),
  'Paris Saint-Germain':       E(160),
  'Paris Saint Germain':       E(160),
  'Monaco':                    E(162),
  'AS Monaco':                 E(162),
  'Lyon':                      E(163),
  'Olympique Lyonnais':        E(163),
  'Marseille':                 E(164),
  'Olympique de Marseille':    E(164),
  'Olympique Marseille':       E(164),
  'Lille':                     E(167),
  'LOSC Lille':                E(167),
  'Nice':                      E(166),
  'OGC Nice':                  E(166),
  'Rennes':                    E(168),
  'Stade Rennais':             E(168),
  'Stade Rennais FC':          E(168),
  'Lens':                      E(165),
  'RC Lens':                   E(165),
  'Strasbourg':                E(170),
  'RC Strasbourg':             E(170),
  'Nantes':                    E(171),
  'FC Nantes':                 E(171),
  'Brest':                     E(4350),
  'Stade Brestois 29':         E(4350),
  'Toulouse':                  E(1321),
  'Toulouse FC':               E(1321),
  'Reims':                     E(1322),
  'Stade de Reims':            E(1322),
  'Le Havre':                  E(2873),
  'HAC Le Havre':              E(2873),
  'Lorient':                   E(4007),
  'FC Lorient':                E(4007),
  'Clermont Foot':             E(54432),
  'Metz':                      E(1317),
  'FC Metz':                   E(1317),
  'Montpellier':               E(173),
  'Montpellier HSC':           E(173),
  'Auxerre':                   E(161),
  'AJ Auxerre':                E(161),
  'Saint-Etienne':             E(176),
  'AS Saint-Étienne':          E(176),
  'Angers':                    E(159),
  'Angers SCO':                E(159),
  'Guingamp':                  E(175),
  'EA Guingamp':               E(175),

  // ── Other European ────────────────────────────────────────────────────────
  'Ajax':                      E(169),
  'AFC Ajax':                  E(169),
  'Porto':                     E(197),
  'FC Porto':                  E(197),
  'Benfica':                   E(199),
  'SL Benfica':                E(199),
  'Sport Lisboa e Benfica':    E(199),
  'Sporting CP':               E(200),
  'Sporting Lisbon':           E(200),
  'Celtic':                    E(441),
  'Celtic FC':                 E(441),
  'Rangers':                   E(452),
  'Rangers FC':                E(452),
  'Galatasaray':               E(219),
  'Fenerbahce':                E(222),
  'Fenerbahçe SK':             E(222),
  'Besiktas':                  E(223),
  'Beşiktaş JK':              E(223),
  'Trabzonspor':               E(221),
  'Shakhtar Donetsk':          E(225),
  'Red Bull Salzburg':         E(3948),
  'RB Salzburg':               E(3948),
  'FC Red Bull Salzburg':      E(3948),
  'Club Brugge':               E(195),
  'Club Brugge KV':            E(195),
  'Anderlecht':                E(193),
  'RSC Anderlecht':            E(193),
  'PSV Eindhoven':             E(172),
  'PSV':                       E(172),
  'Feyenoord':                 E(174),
  'AZ Alkmaar':                E(178),
  'AZ':                        E(178),
  'Dinamo Zagreb':             E(229),
  'GNK Dinamo Zagreb':         E(229),
  'Red Star Belgrade':         E(232),
  'Crvena zvezda':             E(232),
  'Slavia Prague':             E(234),
  'AC Sparta Prague':          E(233),
  'Viktoria Plzen':            E(235),
  'Sheriff Tiraspol':          E(47832),
  'Young Boys':                E(236),
  'BSC Young Boys':            E(236),
  'Zurich':                    E(238),
  'FC Zurich':                 E(238),
  'Basel':                     E(237),
  'FC Basel':                  E(237),
  'PAOK':                      E(2020),
  'Olympiacos':                E(2019),
  'Panathinaikos':             E(2021),

  // ── MLS ───────────────────────────────────────────────────────────────────
  'LA Galaxy':                 E(528),
  'Los Angeles FC':            E(18966),
  'LAFC':                      E(18966),
  'Seattle Sounders':          E(5801),
  'Portland Timbers':          E(9726),
  'Atlanta United':            E(18966),
  'New York City FC':          E(18962),
  'NYCFC':                     E(18962),
  'New York Red Bulls':        E(529),
  'Inter Miami':               E(23980),
  'CF Montréal':               E(8877),
  'Toronto FC':                E(8863),
  'Orlando City':              E(16032),
  'FC Dallas':                 E(531),
  'Houston Dynamo':            E(532),
  'Colorado Rapids':           E(527),
  'Real Salt Lake':            E(536),
  'Vancouver Whitecaps':       E(9726),
  'FC Cincinnati':             E(19736),
  'Columbus Crew':             E(530),
  'Chicago Fire':              E(526),
  'DC United':                 E(525),
  'New England Revolution':    E(535),
  'Philadelphia Union':        E(9731),
  'Nashville SC':              E(20055),
  'Austin FC':                 E(25839),

  // ── NBA ───────────────────────────────────────────────────────────────────
  'Atlanta Hawks':             N('atl'),    'Hawks':      N('atl'),
  'Boston Celtics':            N('bos'),    'Celtics':    N('bos'),
  'Brooklyn Nets':             N('bkn'),    'Nets':       N('bkn'),
  'Charlotte Hornets':         N('cha'),    'Hornets':    N('cha'),
  'Chicago Bulls':             N('chi'),    'Bulls':      N('chi'),
  'Cleveland Cavaliers':       N('cle'),    'Cavaliers':  N('cle'),    'Cavs': N('cle'),
  'Dallas Mavericks':          N('dal'),    'Mavericks':  N('dal'),    'Mavs': N('dal'),
  'Denver Nuggets':            N('den'),    'Nuggets':    N('den'),
  'Detroit Pistons':           N('det'),    'Pistons':    N('det'),
  'Golden State Warriors':     N('gs'),     'Warriors':   N('gs'),
  'Houston Rockets':           N('hou'),    'Rockets':    N('hou'),
  'Indiana Pacers':            N('ind'),    'Pacers':     N('ind'),
  'Los Angeles Clippers':      N('lac'),    'LA Clippers': N('lac'),   'Clippers': N('lac'),
  'Los Angeles Lakers':        N('lal'),    'LA Lakers':  N('lal'),    'Lakers':   N('lal'),
  'Memphis Grizzlies':         N('mem'),    'Grizzlies':  N('mem'),
  'Miami Heat':                N('mia'),    'Heat':       N('mia'),
  'Milwaukee Bucks':           N('mil'),    'Bucks':      N('mil'),
  'Minnesota Timberwolves':    N('min'),    'Timberwolves': N('min'),
  'New Orleans Pelicans':      N('no'),     'Pelicans':   N('no'),
  'New York Knicks':           N('ny'),     'Knicks':     N('ny'),
  'Oklahoma City Thunder':     N('okc'),    'OKC Thunder': N('okc'),   'Thunder': N('okc'),
  'Orlando Magic':             N('orl'),    'Magic':      N('orl'),
  'Philadelphia 76ers':        N('phi'),    '76ers':      N('phi'),
  'Phoenix Suns':              N('phx'),    'Suns':       N('phx'),
  'Portland Trail Blazers':    N('por'),    'Trail Blazers': N('por'),  'Blazers': N('por'),
  'Sacramento Kings':          N('sac'),    'Kings':      N('sac'),
  'San Antonio Spurs':         N('sa'),     'Spurs':      N('sa'),
  'Toronto Raptors':           N('tor'),    'Raptors':    N('tor'),
  'Utah Jazz':                 N('utah'),   'Jazz':       N('utah'),
  'Washington Wizards':        N('wsh'),    'Wizards':    N('wsh'),

  // ── NFL ───────────────────────────────────────────────────────────────────
  'Arizona Cardinals':         F('ari'),
  'Atlanta Falcons':           F('atl'),
  'Baltimore Ravens':          F('bal'),
  'Buffalo Bills':             F('buf'),
  'Carolina Panthers':         F('car'),
  'Chicago Bears':             F('chi'),
  'Cincinnati Bengals':        F('cin'),
  'Cleveland Browns':          F('cle'),
  'Dallas Cowboys':            F('dal'),
  'Denver Broncos':            F('den'),
  'Detroit Lions':             F('det'),
  'Green Bay Packers':         F('gb'),
  'Houston Texans':            F('hou'),
  'Indianapolis Colts':        F('ind'),
  'Jacksonville Jaguars':      F('jax'),
  'Kansas City Chiefs':        F('kc'),
  'Las Vegas Raiders':         F('lv'),
  'Los Angeles Chargers':      F('lac'),
  'LA Chargers':               F('lac'),
  'Los Angeles Rams':          F('lar'),
  'LA Rams':                   F('lar'),
  'Miami Dolphins':            F('mia'),
  'Minnesota Vikings':         F('min'),
  'New England Patriots':      F('ne'),
  'New Orleans Saints':        F('no'),
  'New York Giants':           F('nyg'),
  'New York Jets':             F('nyj'),
  'Philadelphia Eagles':       F('phi'),
  'Pittsburgh Steelers':       F('pit'),
  'San Francisco 49ers':       F('sf'),
  'Seattle Seahawks':          F('sea'),
  'Tampa Bay Buccaneers':      F('tb'),
  'Tennessee Titans':          F('ten'),
  'Washington Commanders':     F('wsh'),
};

/** Lookup a logo URL by team name. Returns null if not found. */
export function getTeamLogo(name: string): string | null {
  if (!name) return null;

  // Exact match
  if (LOGOS[name]) return LOGOS[name];

  // Case-insensitive match
  const lower = name.toLowerCase().trim();
  for (const [key, url] of Object.entries(LOGOS)) {
    if (key.toLowerCase() === lower) return url;
  }

  // Partial match: check if the name starts with or contains a known key
  for (const [key, url] of Object.entries(LOGOS)) {
    const kl = key.toLowerCase();
    if (lower.startsWith(kl) || kl.startsWith(lower)) return url;
  }

  return null;
}
